--- # Update Ubnas and Centnas
- hosts: centos
  become: yes
  user: spl
  gather_facts: no
  connection: ssh
  tasks:
    - name: Update packages
      yum: name='*' state=latest use_backend=yum
    - name: Install package on centos
      yum: name={{ centpkg }} state=latest
- hosts: ubuntu
  become: yes
  user: spl
  gather_facts: no
  connection: ssh
  tasks:
    - name: Update cache and packages
      apt: update_cache=yes upgrade=dist
    - name: Install package on ubuntu
      apt: name={{ ubpkg }} state=latest
